### ISSUE TITLE
Does it work with Rails 5?

### ISSUE THREAD

**Issue by kalsan** [rubiety/validates_lengths_from_database#14]
I've been googling for a while and I found nothing about validates_lengths_from_database and Rails 5.0. Are they compatible? Has it been tested?

**Comment by rubiety** [comment]
This hasn't been explicitly tested with Rails 5, so I can't be sure. Would be open to a pull request to anyone who wants to work on this (am swamped with other work, so can't jump on this in the near term).

**Comment by domcleal** [comment]
Anecdotally I can say that it appears to work fine, our app tests exercise the gem quite a bit and it's shown no issues under 5.0.0.

**Comment by kalsan** [comment]
Thanks for your replies! I did some testing too and it appears to be working. Although, I didn't test it throughly, I think we can give it a go and upgrade our app.
