### ISSUE TITLE
:only and :except options not working

### ISSUE THREAD

**Issue by damiong28** [rubiety/validates_lengths_from_database#15]
I have a model with length validations on 2 columns already (column_A, and column_B). When I add `validates_lengths_from_database :only => [:column_c]`, I will get doubled up error messages for column_a and column_b validations.

Similarly, when I add `validates_lengths_from_database :except => [:column_a, :column_b]` and try again, they are included in the error messages. The only way to remove the doubled up error messages is to remove the call to validates_lengths_from_database from the model entirely. Help please! This is a great gem otherwise. :)

Rails 4.2.7.1 , Ruby 2.3.1

**Comment by rubiety** [comment]
@damiong28 Can you push a repository somewhere illustrating/replicating this problem? The behavior you are describing does not make sense to me: `validates_lengths_from_database` definitely only validates for the columns you explicitly place in `:only =>` (if you've included that as an option), per this code in `lib/validates_lengths_from_database.rb`:

```ruby
if options[:only]
  columns_to_validate = options[:only].map(&:to_s)
else
  columns_to_validate = self.class.column_names.map(&:to_s)
  columns_to_validate -= options[:except].map(&:to_s) if options[:except]
end

columns_to_validate.each do |column|
  ...
  ActiveModel::Validations::LengthValidator.new(:maximum => column_limit, :allow_blank => true, :attributes => [column]).validate(self)
end
```

So I'm not really seeing how you could be getting doubled-up validations, unless those validations are somehow defined multiple times in your implementation code.

**Comment by damiong28** [comment]
I spun up a sample app and copied my validations yet I'm unable to reproduce the behavior. The problem must be with my app somewhere. I did find a work around for my situation though (calling uniq when the error messages are displayed) so I'll close this issue. Thanks!
