### ISSUE TITLE
Lazy-Evaluating Length from DB

### ISSUE THREAD

**Issue by rubiety** [rubiety/validates_lengths_from_database#3]
Since this doesn't lazy-evaluate table naming, it doesn't really work on an STI base class (or on ActiveRecord::Base). This should probably be redone to support this.

**Comment by iNecas** [comment]
Seems like 6 years after the original issue, this actually might be resolved by https://github.com/rubiety/validates_lengths_from_database/pull/12 :)

**Comment by rubiety** [comment]
Yes this should be resolved now, closing.
